version: '3'
services:
  web:
    image: danielapb/url_shortener:1
    command: bundle exec puma -p ${PORT:-8080}
    volumes:
      - .:/url_shortener
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - PORT=8080
      - RACK_ENV=development

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    volumes:
      - redis_data:/data

  sidekiq:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/url_shortener
    depends_on:
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/12

volumes:
  redis_data:
    driver: local
