version: '3'
services:
  web:
    #image: danielapb/bowling_kata:1
    build: .
    command: bundle exec puma -p ${PORT:-8080}
    volumes:
      - .:/url_shortener
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - PORT=8080
      - RACK_ENV=development

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
